name: "Generate Ued manifest"
description: "生成ued所需的所有所需描述文件并且推送至website项目"
inputs:
  github_token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        path: ./workspace
    - run: rm -rf ./manifest && mkdir ./manifest
      shell: bash
    - run: |
        cd ./workspace
        npx @kne/npm-tools manifest
        cp -r ./build/* ./manifest
        rm -rf ./build
      shell: bash
    - uses: actions-js/push@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: master
        directory: ./workspace
        repository: 'kne-union/static-data'
