name: "Generate Ued manifest"
description: "生成ued所需的所有所需描述文件并且推送至website项目"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        path: ./workspace
    - run: rm -rf ./manifest && mkdir ./manifest
      shell: bash
    - run: |
        cd ./workspace
        npx @kne/npm-tools manifest
        cp -r ./build/* ../manifest
        rm -rf ./build
        git config --global user.name "actions"
        git add ./manifest
        git commit -am "Regenerate Manifest By Actions"
        git push origin master
      shell: bash
