name: "Generate Ued manifest"
description: "生成ued所需的所有所需描述文件并且推送至website项目"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        path: ./workspace
    - run: rm -rf ./manifest && mkdir ./manifest
      shell: bash
    - run: |
        cd ./workspace
        npx @kne/npm-tools manifest
        cp -r ./build/* ../manifest
      shell: bash
    - run: rm -rf ./workspace
      shell: bash
    - run: git commit -am "Regenerate Manifest By Actions"
      shell: bash
    - run: git push origin master
      shell: bash
