name: "Generate Ued manifest"
description: "生成ued所需的所有所需描述文件并且推送至website项目"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        path: ./workspace
    - run: rm -rf ./manifest && mkdir ./manifest
      shell: bash
    - run: |
        cd ./workspace
        npx @kne/npm-tools manifest
        cp -r ./build/* ../manifest
        rm -rf ./build
        rm -rf .git
      shell: bash
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./workspace
