name: "Generate Ued manifest"
description: "生成ued所需的所有所需描述文件并且推送至website项目"
inputs:
  token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        token: ${{ inputs.token }}
    - run: |
        rm -rf ./manifest && mkdir ./manifest
        npx @kne/npm-tools manifest
        cp -r ./build/* ./manifest
        rm -rf ./build
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: 'master'
